GET https://taxi-queue-app-udu0.onrender.com/api/passenger/queue

###

GET https://taxi-queue-app-udu0.onrender.com/api/taxi/queue

###

POST https://taxi-queue-app-udu0.onrender.com/api/passenger/join
Content-Type: application/json

{
    "passenger_queue_count" : 1
}

###

POST https://taxi-queue-app-udu0.onrender.com/api/passenger/leave
Content-Type: application/json

{
    "passenger_queue_count" : 1
}

###

POST https://taxi-queue-app-udu0.onrender.com/api/taxi/join
Content-Type: application/json

{
    "taxi_queue_count" : 1
}

###

POST https://taxi-queue-app-udu0.onrender.com/api/taxi/depart
Content-Type: application/json

{
    "passenger_queue_count" : 1,
    "taxi_queue_count" : 1
}